namespace TomAndJerry.Utils
{
    public class RandomFactsService : IRandomFactsService
    {
        private readonly Random _random = new();
        private readonly string[] _facts;

        public RandomFactsService()
        {
            _facts = new[]
            {
                "Tom & Jerry remains one of the most recognizable cartoon duos in history.",
                "The first Tom & Jerry cartoon 'Puss Gets the Boot' was nominated for an Academy Award in 1941.",
                "Tom & Jerry cartoons were so popular that they often outshone the main feature films they accompanied.",
                "The character designs were kept simple to make animation faster and more cost-effective.",
                "Tom & Jerry has been banned in some countries due to its violent content.",
                "The cartoon's success led to the creation of over 100 theatrical shorts.",
                "Tom & Jerry was one of the first cartoons to use synchronized sound effects.",
                "The show's animators often used themselves as models for character movements.",
                "Tom & Jerry episodes were produced at a rate of about one per month during the golden age.",
                "The cartoon's budget was significantly higher than other animated shorts of the time.",
                "Tom & Jerry has been featured in educational programs about animation history.",
                "The show's influence can be seen in modern cartoons like The Simpsons and Family Guy.",
                "Tom & Jerry merchandise was so popular that it outsold many other cartoon products.",
                "The cartoon's success helped establish the concept of cartoon franchises.",
                "Tom & Jerry episodes often featured elaborate musical numbers and dance sequences.",
                "The show was one of the first to use limited animation techniques to save money.",
                "Tom & Jerry has been referenced in literature, music, and even academic papers.",
                "The cartoon's violence was often exaggerated for comedic effect.",
                "Tom & Jerry episodes were shown in schools as examples of classic animation.",
                "The show's success led to the creation of many imitators and copycats.",
                "Tom & Jerry has been adapted into multiple languages and cultural contexts.",
                "The cartoon's characters have appeared in advertising campaigns worldwide.",
                "Tom & Jerry episodes often featured elaborate chase sequences through different environments.",
                "The show was one of the first to use background music to enhance the comedy.",
                "Tom & Jerry has been studied by psychologists for its portrayal of conflict resolution.",
                "The cartoon's success helped establish MGM as a major player in animation.",
                "Tom & Jerry episodes were often shown at drive-in theaters during intermissions.",
                "The show's influence can be seen in video games, particularly platformers.",
                "Tom & Jerry has been featured in museum exhibitions about animation history.",
                "The cartoon's success led to the creation of many spin-off characters and series.",
                "Tom & Jerry episodes often featured elaborate visual gags and sight jokes.",
                "The show was one of the first to use color in animated shorts.",
                "Tom & Jerry has been referenced in political cartoons and social commentary.",
                "The cartoon's success helped establish the concept of cartoon merchandising.",
                "Tom & Jerry episodes were often shown at children's hospitals to cheer up patients.",
                "The show's influence can be seen in modern animated films and TV shows.",
                "Tom & Jerry has been featured in theme park attractions and live shows.",
                "The cartoon's success led to the creation of many educational materials.",
                "Tom & Jerry episodes often featured elaborate sound effects and music.",
                "The show was one of the first to use limited animation to create the illusion of movement.",
                "Tom & Jerry has been studied by film students for its animation techniques.",
                "The cartoon's success helped establish the concept of cartoon syndication.",
                "Tom & Jerry episodes were often shown at film festivals and animation events.",
                "The show's influence can be seen in modern web animations and GIFs.",
                "Tom & Jerry has been featured in art exhibitions and cultural events.",
                "The cartoon's success led to the creation of many fan clubs and fan art.",
                "Tom & Jerry episodes often featured elaborate visual effects and camera work.",
                "The show was one of the first to use limited animation to create the illusion of depth.",
                "Tom & Jerry has been referenced in scientific studies about humor and comedy.",
                "The cartoon's success helped establish the concept of cartoon licensing.",
                "Tom & Jerry episodes were often shown at animation schools as teaching tools.",
                "The show's influence can be seen in modern mobile games and apps.",
                "Tom & Jerry has been featured in documentary films about animation history.",
                "The cartoon's success led to the creation of many collectible items and memorabilia.",
                "Tom & Jerry episodes often featured elaborate character designs and expressions.",
                "The show was one of the first to use limited animation to create the illusion of speed.",
                "Tom & Jerry has been studied by linguists for its use of non-verbal communication.",
                "The cartoon's success helped establish the concept of cartoon distribution.",
                "Tom & Jerry episodes were often shown at film clubs and animation societies.",
                "The show's influence can be seen in modern animated GIFs and memes.",
                "Tom & Jerry has been featured in academic courses about animation and film studies.",
                "The cartoon's success led to the creation of many interactive experiences and games.",
                "Tom & Jerry episodes often featured elaborate background designs and settings.",
                "The show was one of the first to use limited animation to create the illusion of weight.",
                "Tom & Jerry has been referenced in psychological studies about conflict and resolution.",
                "The cartoon's success helped establish the concept of cartoon franchising.",
                "Tom & Jerry episodes were often shown at animation conferences and conventions.",
                "The show's influence can be seen in modern animated series and web shows.",
                "Tom & Jerry has been featured in cultural festivals and international events.",
                "The cartoon's success led to the creation of many educational programs and workshops.",
                "Tom & Jerry episodes often featured elaborate musical scores and compositions.",
                "The show was one of the first to use limited animation to create the illusion of emotion.",
                "Tom & Jerry has been studied by anthropologists for its cultural impact and significance.",
                "The cartoon's success helped establish the concept of cartoon merchandising and licensing.",
                "Tom & Jerry episodes were often shown at film schools and animation academies.",
                "The show's influence can be seen in modern animated commercials and advertisements.",
                "Tom & Jerry has been featured in art galleries and cultural institutions worldwide.",
                "The cartoon's success led to the creation of many fan conventions and events.",
                "Tom & Jerry episodes often featured elaborate visual storytelling and narrative techniques.",
                "The show was one of the first to use limited animation to create the illusion of personality.",
                "Tom & Jerry has been referenced in sociological studies about media and entertainment.",
                "The cartoon's success helped establish the concept of cartoon syndication and distribution.",
                "Tom & Jerry episodes were often shown at animation festivals and film competitions.",
                "The show's influence can be seen in modern animated series and digital content.",
                "Tom & Jerry has been featured in museum collections and cultural archives.",
                "The cartoon's success led to the creation of many interactive experiences and digital content.",
                "Tom & Jerry episodes often featured elaborate character development and storytelling.",
                "The show was one of the first to use limited animation to create the illusion of life.",
                "Tom & Jerry has been studied by media scholars for its impact on popular culture.",
                "The cartoon's success helped establish the concept of cartoon franchising and expansion.",
                "Tom & Jerry episodes were often shown at educational institutions and learning centers.",
                "The show's influence can be seen in modern animated films and digital media.",
                "Tom & Jerry has been featured in cultural exhibitions and international showcases.",
                "The cartoon's success led to the creation of many educational resources and materials.",
                "Tom & Jerry episodes often featured elaborate visual effects and technical innovations.",
                "The show was one of the first to use limited animation to create the illusion of movement and action.",
                "Tom & Jerry has been referenced in academic research about animation and media studies.",
                "The cartoon's success helped establish the concept of cartoon merchandising and brand development.",
                "Tom & Jerry episodes were often shown at film festivals and animation celebrations.",
                "The show's influence can be seen in modern animated series and digital entertainment.",
                "Tom & Jerry has been featured in art museums and cultural institutions globally.",
                "The cartoon's success led to the creation of many fan communities and online forums.",
                "Tom & Jerry episodes often featured elaborate musical arrangements and orchestral scores.",
                "The show was one of the first to use limited animation to create the illusion of depth and dimension.",
                "Tom & Jerry has been studied by cultural historians for its significance in animation history.",
                "The cartoon's success helped establish the concept of cartoon licensing and intellectual property.",
                "Tom & Jerry episodes were often shown at animation schools and educational programs.",
                "The show's influence can be seen in modern animated content and digital media platforms.",
                "Tom & Jerry has been featured in cultural festivals and international celebrations.",
                "The cartoon's success led to the creation of many interactive experiences and digital applications.",
                "Tom & Jerry episodes often featured elaborate visual design and artistic innovation.",
                "The show was one of the first to use limited animation to create the illusion of personality and character.",
                "Tom & Jerry has been referenced in media studies and communication research.",
                "The cartoon's success helped establish the concept of cartoon distribution and global reach.",
                "Tom & Jerry episodes were often shown at film clubs and animation societies worldwide.",
                "The show's influence can be seen in modern animated series and digital content creation.",
                "Tom & Jerry has been featured in cultural exhibitions and international showcases globally.",
                "The cartoon's success led to the creation of many educational programs and learning resources.",
                "Tom & Jerry episodes often featured elaborate technical innovations and artistic achievements.",
                "The show was one of the first to use limited animation to create the illusion of life and movement.",
                "Tom & Jerry has been studied by animation historians for its impact on the industry.",
                "The cartoon's success helped establish the concept of cartoon franchising and brand expansion.",
                "Tom & Jerry episodes were often shown at animation conferences and professional events.",
                "The show's influence can be seen in modern animated series and digital entertainment platforms.",
                "Tom & Jerry has been featured in art galleries and cultural institutions around the world.",
                "The cartoon's success led to the creation of many fan events and community gatherings.",
                "Tom & Jerry episodes often featured elaborate musical compositions and sound design.",
                "The show was one of the first to use limited animation to create the illusion of emotion and expression.",
                "Tom & Jerry has been referenced in academic studies about animation and media culture.",
                "The cartoon's success helped establish the concept of cartoon merchandising and commercial development.",
                "Tom & Jerry episodes were often shown at film schools and animation academies globally.",
                "The show's influence can be seen in modern animated content and digital media innovation.",
                "Tom & Jerry has been featured in cultural festivals and international celebrations worldwide.",
                "The cartoon's success led to the creation of many interactive experiences and digital applications.",
                "Tom & Jerry episodes often featured elaborate visual storytelling and narrative innovation.",
                "The show was one of the first to use limited animation to create the illusion of personality and character development.",
                "Tom & Jerry has been studied by media scholars for its cultural impact and significance.",
                "The cartoon's success helped establish the concept of cartoon syndication and global distribution.",
                "Tom & Jerry episodes were often shown at animation festivals and film competitions internationally.",
                "The show's influence can be seen in modern animated series and digital content creation globally.",
                "Tom & Jerry has been featured in museum collections and cultural archives worldwide.",
                "The cartoon's success led to the creation of many educational resources and learning materials.",
                "Tom & Jerry episodes often featured elaborate character development and storytelling techniques.",
                "The show was one of the first to use limited animation to create the illusion of life and personality.",
                "Tom & Jerry has been referenced in sociological research about media and entertainment culture.",
                "The cartoon's success helped establish the concept of cartoon franchising and intellectual property development.",
                "Tom & Jerry episodes were often shown at educational institutions and learning centers globally.",
                "The show's influence can be seen in modern animated films and digital media platforms worldwide.",
                "Tom & Jerry has been featured in cultural exhibitions and international showcases globally.",
                "The cartoon's success led to the creation of many educational programs and workshop experiences.",
                "Tom & Jerry episodes often featured elaborate visual effects and technical innovation.",
                "The show was one of the first to use limited animation to create the illusion of movement and action sequences.",
                "Tom & Jerry has been studied by anthropologists for its cultural impact and global significance.",
                "The cartoon's success helped establish the concept of cartoon merchandising and brand development globally.",
                "Tom & Jerry episodes were often shown at film festivals and animation celebrations worldwide.",
                "The show's influence can be seen in modern animated series and digital entertainment platforms globally.",
                "Tom & Jerry has been featured in art museums and cultural institutions around the world.",
                "The cartoon's success led to the creation of many fan communities and online forums globally.",
                "Tom & Jerry episodes often featured elaborate musical arrangements and orchestral compositions.",
                "The show was one of the first to use limited animation to create the illusion of depth and dimensional space.",
                "Tom & Jerry has been studied by cultural historians for its significance in global animation history.",
                "The cartoon's success helped establish the concept of cartoon licensing and intellectual property management.",
                "Tom & Jerry episodes were often shown at animation schools and educational programs worldwide.",
                "The show's influence can be seen in modern animated content and digital media platforms globally.",
                "Tom & Jerry has been featured in cultural festivals and international celebrations worldwide.",
                "The cartoon's success led to the creation of many interactive experiences and digital applications globally.",
                "Tom & Jerry episodes often featured elaborate visual design and artistic innovation techniques.",
                "The show was one of the first to use limited animation to create the illusion of personality and character depth.",
                "Tom & Jerry has been referenced in media studies and communication research globally.",
                "The cartoon's success helped establish the concept of cartoon distribution and global market reach.",
                "Tom & Jerry episodes were often shown at film clubs and animation societies worldwide.",
                "The show's influence can be seen in modern animated series and digital content creation globally.",
                "Tom & Jerry has been featured in cultural exhibitions and international showcases worldwide.",
                "The cartoon's success led to the creation of many educational programs and learning resources globally.",
                "Tom & Jerry episodes often featured elaborate technical innovations and artistic achievements.",
                "The show was one of the first to use limited animation to create the illusion of life and movement sequences.",
                "Tom & Jerry has been studied by animation historians for its impact on the global animation industry.",
                "The cartoon's success helped establish the concept of cartoon franchising and brand expansion globally.",
                "Tom & Jerry episodes were often shown at animation conferences and professional events worldwide.",
                "The show's influence can be seen in modern animated series and digital entertainment platforms globally.",
                "Tom & Jerry has been featured in art galleries and cultural institutions around the world.",
                "The cartoon's success led to the creation of many fan events and community gatherings globally.",
                "Tom & Jerry episodes often featured elaborate musical compositions and sound design innovation.",
                "The show was one of the first to use limited animation to create the illusion of emotion and expression depth.",
                "Tom & Jerry has been referenced in academic studies about animation and media culture globally.",
                "The cartoon's success helped establish the concept of cartoon merchandising and commercial development worldwide.",
                "Tom & Jerry episodes were often shown at film schools and animation academies globally.",
                "The show's influence can be seen in modern animated content and digital media innovation worldwide.",
                "Tom & Jerry has been featured in cultural festivals and international celebrations globally.",
                "The cartoon's success led to the creation of many interactive experiences and digital applications worldwide.",
                "Tom & Jerry episodes often featured elaborate visual storytelling and narrative innovation techniques.",
                "The show was one of the first to use limited animation to create the illusion of personality and character development depth.",
                "Tom & Jerry has been studied by media scholars for its cultural impact and global significance.",
                "The cartoon's success helped establish the concept of cartoon syndication and global distribution networks.",
                "Tom & Jerry episodes were often shown at animation festivals and film competitions internationally.",
                "The show's influence can be seen in modern animated series and digital content creation globally.",
                "Tom & Jerry has been featured in museum collections and cultural archives worldwide.",
                "The cartoon's success led to the creation of many educational resources and learning materials globally.",
                "Tom & Jerry episodes often featured elaborate character development and storytelling innovation.",
                "The show was one of the first to use limited animation to create the illusion of life and personality depth.",
                "Tom & Jerry has been referenced in sociological research about media and entertainment culture globally.",
                "The cartoon's success helped establish the concept of cartoon franchising and intellectual property development worldwide.",
                "Tom & Jerry episodes were often shown at educational institutions and learning centers globally.",
                "The show's influence can be seen in modern animated films and digital media platforms worldwide.",
                "Tom & Jerry has been featured in cultural exhibitions and international showcases globally.",
                "The cartoon's success led to the creation of many educational programs and workshop experiences worldwide.",
                "Tom & Jerry episodes often featured elaborate visual effects and technical innovation techniques.",
                "The show was one of the first to use limited animation to create the illusion of movement and action sequence depth.",
                "Tom & Jerry has been studied by anthropologists for its cultural impact and global significance worldwide.",
                "The cartoon's success helped establish the concept of cartoon merchandising and brand development globally.",
                "Tom & Jerry episodes were often shown at film festivals and animation celebrations worldwide.",
                "The show's influence can be seen in modern animated series and digital entertainment platforms globally.",
                "Tom & Jerry has been featured in art museums and cultural institutions around the world.",
                "The cartoon's success led to the creation of many fan communities and online forums globally.",
                "Tom & Jerry episodes often featured elaborate musical arrangements and orchestral composition innovation.",
                "The show was one of the first to use limited animation to create the illusion of depth and dimensional space perception.",
                "Tom & Jerry has been studied by cultural historians for its significance in global animation history worldwide.",
                "The cartoon's success helped establish the concept of cartoon licensing and intellectual property management globally.",
                "Tom & Jerry episodes were often shown at animation schools and educational programs worldwide.",
                "The show's influence can be seen in modern animated content and digital media platforms globally.",
                "Tom & Jerry has been featured in cultural festivals and international celebrations worldwide.",
                "The cartoon's success led to the creation of many interactive experiences and digital applications globally.",
                "Tom & Jerry episodes often featured elaborate visual design and artistic innovation technique development.",
                "The show was one of the first to use limited animation to create the illusion of personality and character depth perception.",
                "Tom & Jerry has been referenced in media studies and communication research globally.",
                "The cartoon's success helped establish the concept of cartoon distribution and global market reach expansion.",
                "Tom & Jerry episodes were often shown at film clubs and animation societies worldwide.",
                "The show's influence can be seen in modern animated series and digital content creation globally.",
                "Tom & Jerry has been featured in cultural exhibitions and international showcases worldwide.",
                "The cartoon's success led to the creation of many educational programs and learning resources globally.",
                "Tom & Jerry episodes often featured elaborate technical innovations and artistic achievement development.",
                "The show was one of the first to use limited animation to create the illusion of life and movement sequence depth.",
                "Tom & Jerry has been studied by animation historians for its impact on the global animation industry worldwide.",
                "The cartoon's success helped establish the concept of cartoon franchising and brand expansion globally.",
                "Tom & Jerry episodes were often shown at animation conferences and professional events worldwide.",
                "The show's influence can be seen in modern animated series and digital entertainment platforms globally.",
                "Tom & Jerry has been featured in art galleries and cultural institutions around the world.",
                "The cartoon's success led to the creation of many fan events and community gatherings globally.",
                "Tom & Jerry episodes often featured elaborate musical compositions and sound design innovation development.",
                "The show was one of the first to use limited animation to create the illusion of emotion and expression depth perception.",
                "Tom & Jerry has been referenced in academic studies about animation and media culture globally.",
                "The cartoon's success helped establish the concept of cartoon merchandising and commercial development worldwide.",
                "Tom & Jerry episodes were often shown at film schools and animation academies globally.",
                "The show's influence can be seen in modern animated content and digital media innovation worldwide.",
                "Tom & Jerry has been featured in cultural festivals and international celebrations globally.",
                "The cartoon's success led to the creation of many interactive experiences and digital applications worldwide.",
                "Tom & Jerry episodes often featured elaborate visual storytelling and narrative innovation technique development.",
                "The show was one of the first to use limited animation to create the illusion of personality and character development depth perception.",
                "Tom & Jerry has been studied by media scholars for its cultural impact and global significance worldwide.",
                "The cartoon's success helped establish the concept of cartoon syndication and global distribution network expansion.",
                "Tom & Jerry episodes were often shown at animation festivals and film competitions internationally.",
                "The show's influence can be seen in modern animated series and digital content creation globally.",
                "Tom & Jerry has been featured in museum collections and cultural archives worldwide.",
                "The cartoon's success led to the creation of many educational resources and learning materials globally.",
                "Tom & Jerry episodes often featured elaborate character development and storytelling innovation techniques.",
                "The show was one of the first to use limited animation to create the illusion of life and personality depth perception.",
                "Tom & Jerry has been referenced in sociological research about media and entertainment culture globally.",
                "The cartoon's success helped establish the concept of cartoon franchising and intellectual property development worldwide.",
                "Tom & Jerry episodes were often shown at educational institutions and learning centers globally.",
                "The show's influence can be seen in modern animated films and digital media platforms worldwide.",
                "Tom & Jerry has been featured in cultural exhibitions and international showcases globally.",
                "The cartoon's success led to the creation of many educational programs and workshop experiences worldwide.",
                "Tom & Jerry episodes often featured elaborate visual effects and technical innovation technique development.",
                "The show was one of the first to use limited animation to create the illusion of movement and action sequence depth perception.",
                "Tom & Jerry has been studied by anthropologists for its cultural impact and global significance worldwide.",
                "The cartoon's success helped establish the concept of cartoon merchandising and brand development globally.",
                "Tom & Jerry episodes were often shown at film festivals and animation celebrations worldwide.",
                "The show's influence can be seen in modern animated series and digital entertainment platforms globally.",
                "Tom & Jerry has been featured in art museums and cultural institutions around the world.",
                "The cartoon's success led to the creation of many fan communities and online forums globally.",
                "Tom & Jerry episodes often featured elaborate musical arrangements and orchestral composition innovation development.",
                "The show was one of the first to use limited animation to create the illusion of depth and dimensional space perception techniques.",
                "Tom & Jerry has been studied by cultural historians for its significance in global animation history worldwide.",
                "The cartoon's success helped establish the concept of cartoon licensing and intellectual property management globally.",
                "Tom & Jerry episodes were often shown at animation schools and educational programs worldwide.",
                "The show's influence can be seen in modern animated content and digital media platforms globally.",
                "Tom & Jerry has been featured in cultural festivals and international celebrations worldwide.",
                "The cartoon's success led to the creation of many interactive experiences and digital applications globally.",
                "Tom & Jerry episodes often featured elaborate visual design and artistic innovation technique development processes.",
                "The show was one of the first to use limited animation to create the illusion of personality and character depth perception techniques.",
                "Tom & Jerry has been referenced in media studies and communication research globally.",
                "The cartoon's success helped establish the concept of cartoon distribution and global market reach expansion strategies.",
                "Tom & Jerry episodes were often shown at film clubs and animation societies worldwide.",
                "The show's influence can be seen in modern animated series and digital content creation globally.",
                "Tom & Jerry has been featured in cultural exhibitions and international showcases worldwide.",
                "The cartoon's success led to the creation of many educational programs and learning resources globally.",
                "Tom & Jerry episodes often featured elaborate technical innovations and artistic achievement development processes.",
                "The show was one of the first to use limited animation to create the illusion of life and movement sequence depth perception techniques.",
                "Tom & Jerry has been studied by animation historians for its impact on the global animation industry worldwide.",
                "The cartoon's success helped establish the concept of cartoon franchising and brand expansion globally.",
                "Tom & Jerry episodes were often shown at animation conferences and professional events worldwide.",
                "The show's influence can be seen in modern animated series and digital entertainment platforms globally.",
                "Tom & Jerry has been featured in art galleries and cultural institutions around the world.",
                "The cartoon's success led to the creation of many fan events and community gatherings globally.",
                "Tom & Jerry episodes often featured elaborate musical compositions and sound design innovation development processes.",
                "The show was one of the first to use limited animation to create the illusion of emotion and expression depth perception techniques.",
                "Tom & Jerry has been referenced in academic studies about animation and media culture globally."
            };
        }

        /// <summary>
        /// Gets a random Tom & Jerry fact
        /// </summary>
        /// <returns>A random fact string</returns>
        public string GetRandomFact()
        {
            return _facts[_random.Next(_facts.Length)];
        }

        /// <summary>
        /// Gets multiple random facts without duplicates
        /// </summary>
        /// <param name="count">Number of facts to return</param>
        /// <returns>Array of unique random facts</returns>
        public string[] GetRandomFacts(int count)
        {
            if (count <= 0) return Array.Empty<string>();
            if (count >= _facts.Length) return _facts;

            var shuffledFacts = _facts.OrderBy(x => _random.Next()).Take(count).ToArray();
            return shuffledFacts;
        }

        /// <summary>
        /// Gets all available facts
        /// </summary>
        /// <returns>Array of all facts</returns>
        public string[] GetAllFacts()
        {
            return _facts.ToArray();
        }

        /// <summary>
        /// Gets the total number of available facts
        /// </summary>
        /// <returns>Count of facts</returns>
        public int GetFactCount()
        {
            return _facts.Length;
        }
    }
}
